"""Business logic for NOTIFICATION.

Source: app/models/notification.py, docs/database-design.md Section 1.14.

Business rule implemented: a user may only view, mark as read, or dismiss
their own notifications.

`notify()` (Task 21) is the creation logic a prior task explicitly
deferred ("notifications are meant to be generated by other parts of the
system as a side effect of events... but implementing that is explicitly
out of scope for THIS task" - that task's own words). This is that other
task. `notify()` is the single entry point every business-action service
(e.g. `JobMatchService`) calls - it does two things, in order:

    1. Persists a `Notification` row (in-app history - Step 14/Task 21's
       `/notifications`).
    2. Delegates actual push delivery to `PushService` (Step 8's
       diagram: Application Service -> Notification Service ->
       Firebase Admin SDK -> FCM - `PushService` IS the "Firebase Admin
       SDK" box from the caller's point of view; callers only ever touch
       this class, never `PushService` or `firebase_admin` directly).

Callers are expected to call this AFTER their own transaction has
committed (Step 9) and to swallow any exception it raises rather than let
it fail their own already-successful business operation (Step 18) - see
`JobMatchService.apply_to_job`/`.review_application` for the established
pattern (`try/except Exception: logger.exception(...)` around the call).
`notify()` itself commits its own `Notification` row separately from
whatever transaction the caller was in, and `PushService` never raises at
all (see its own module docstring) - so the only way this method can
raise is a genuine DB failure persisting the notification row, which a
caller must still not let break its own already-completed action.
"""

import logging
import uuid
from collections.abc import Sequence

from app.models.notification import Notification
from app.repositories.exceptions import RepositoryError
from app.repositories.notification_repository import NotificationRepository
from app.services.base import BaseService
from app.services.exceptions import ResourceNotFoundError, UnauthorizedOperationError
from app.services.push_service import PushService

logger = logging.getLogger(__name__)


class NotificationService(BaseService):
    def __init__(self, session) -> None:  # noqa: ANN001
        super().__init__(session)
        self._notifications = NotificationRepository(session)
        self._push = PushService(session)

    async def notify(
        self,
        user_id: uuid.UUID,
        *,
        notification_type: str,
        title: str,
        message: str,
        entity_type: str | None = None,
        entity_id: uuid.UUID | None = None,
    ) -> Notification:
        """Creates the in-app `Notification` record, then pushes via FCM.
        `title` is push-only (a short heading FCM shows in the system
        tray) - not persisted, since the `Notification` model has no
        title field; `message` is both the persisted body text AND the
        push body, so `/notifications` history and what the device
        displayed always agree.

        Step 10's structured payload - `type`/`entity_type`/`entity_id`,
        never anything more (no worker/business names, no job budget -
        Step 7/10: "Do not expose sensitive information in the
        notification payload" / "Do not send unnecessary personal/private
        information")."""
        try:
            notification = await self._notifications.create(
                user_id=user_id,
                type=notification_type,
                message=message,
                is_read=False,
                entity_type=entity_type,
                entity_id=entity_id,
            )
        except RepositoryError as exc:
            await self._rollback_and_raise(exc)
        await self._commit()

        data = {"type": notification_type}
        if entity_type is not None:
            data["entity_type"] = entity_type
        if entity_id is not None:
            data["entity_id"] = str(entity_id)

        result = await self._push.send_to_user(user_id, title=title, body=message, data=data)
        logger.info(
            "Notification %s (%s) for user %s: pushed to %d/%d device(s), %d invalid token(s) removed",
            notification.notification_id,
            notification_type,
            user_id,
            result.sent,
            result.attempted,
            result.invalid_tokens_removed,
        )
        return notification

    async def list_for_user(
        self,
        user_id: uuid.UUID,
        requester_id: uuid.UUID,
        *,
        unread_only: bool = False,
        limit: int = 100,
        offset: int = 0,
    ) -> Sequence[Notification]:
        if requester_id != user_id:
            raise UnauthorizedOperationError("You can only view your own notifications.")
        return await self._notifications.list_by_user(
            user_id, unread_only=unread_only, limit=limit, offset=offset
        )

    async def _get_owned(self, notification_id: uuid.UUID, requester_id: uuid.UUID) -> Notification:
        notification = await self._notifications.get_by_id(notification_id)
        if notification is None:
            raise ResourceNotFoundError("Notification", notification_id)
        if requester_id != notification.user_id:
            raise UnauthorizedOperationError("You can only manage your own notifications.")
        return notification

    async def mark_read(self, notification_id: uuid.UUID, requester_id: uuid.UUID, *, is_read: bool = True) -> Notification:
        notification = await self._get_owned(notification_id, requester_id)
        try:
            updated = await self._notifications.update(notification, is_read=is_read)
        except RepositoryError as exc:
            await self._rollback_and_raise(exc)
        await self._commit()
        return updated

    async def dismiss(self, notification_id: uuid.UUID, requester_id: uuid.UUID) -> None:
        notification = await self._get_owned(notification_id, requester_id)
        try:
            await self._notifications.delete(notification)
        except RepositoryError as exc:
            await self._rollback_and_raise(exc)
        await self._commit()
