"""add device_tokens table and notification message/created_at/entity fields

Revision ID: 397cc3c109e1
Revises: 3a9b73f0c612
Create Date: 2026-08-12 20:43:30.669299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397cc3c109e1'
down_revision: Union[str, None] = '3a9b73f0c612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('device_token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=4096), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_device_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('device_token_id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_device_tokens_token'))
    )
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('message', sa.String(length=500), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'message')
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
