"""add profile_image_url to workers and hiring_parties

Revision ID: 3a9b73f0c612
Revises: 9672eb8392af
Create Date: 2026-08-12 16:34:39.801152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9b73f0c612'
down_revision: Union[str, None] = '9672eb8392af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_parties', sa.Column('profile_image_url', sa.String(length=2048), nullable=True))
    op.add_column('workers', sa.Column('profile_image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'profile_image_url')
    op.drop_column('hiring_parties', 'profile_image_url')
    # ### end Alembic commands ###
