"""add image_url to jobs

Revision ID: 64f9b9b0c0cf
Revises: 27234a8b28a8
Create Date: 2026-08-16 02:14:01.383245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f9b9b0c0cf'
down_revision: Union[str, None] = '27234a8b28a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'image_url')
    # ### end Alembic commands ###
