"""create initial ego schema

Revision ID: 9672eb8392af
Revises: 
Create Date: 2026-08-10 23:18:40.657893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9672eb8392af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_job_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_job_categories_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('hiring_parties',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=True),
    sa.Column('verified_badge', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_hiring_parties_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_hiring_parties'))
    )
    op.create_table('kyc',
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_kyc_user_id_users')),
    sa.PrimaryKeyConstraint('kyc_id', name=op.f('pk_kyc'))
    )
    op.create_index(op.f('ix_kyc_user_id'), 'kyc', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('workers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('experience', sa.SmallInteger(), nullable=True),
    sa.Column('expected_wage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.String(length=30), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('service_locations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('verified_badge', sa.Boolean(), nullable=False),
    sa.CheckConstraint('experience >= 0', name=op.f('ck_workers_experience_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_workers_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_workers'))
    )
    op.create_table('connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('hiring_party_id', sa.UUID(), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.CheckConstraint('jobs_completed >= 0', name=op.f('ck_connections_jobs_completed_non_negative')),
    sa.ForeignKeyConstraint(['hiring_party_id'], ['hiring_parties.user_id'], name=op.f('fk_connections_hiring_party_id_hiring_parties')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.user_id'], name=op.f('fk_connections_worker_id_workers')),
    sa.PrimaryKeyConstraint('connection_id', name=op.f('pk_connections')),
    sa.UniqueConstraint('worker_id', 'hiring_party_id', name='uq_connections_worker_hiring_party')
    )
    op.create_index(op.f('ix_connections_hiring_party_id'), 'connections', ['hiring_party_id'], unique=False)
    op.create_index(op.f('ix_connections_worker_id'), 'connections', ['worker_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('hiring_party_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_categories.category_id'], name=op.f('fk_jobs_category_id_job_categories')),
    sa.ForeignKeyConstraint(['hiring_party_id'], ['hiring_parties.user_id'], name=op.f('fk_jobs_hiring_party_id_hiring_parties')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_category_id'), 'jobs', ['category_id'], unique=False)
    op.create_index(op.f('ix_jobs_hiring_party_id'), 'jobs', ['hiring_party_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('withdrawals',
    sa.Column('withdrawal_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_withdrawals_amount_positive')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.user_id'], name=op.f('fk_withdrawals_worker_id_workers')),
    sa.PrimaryKeyConstraint('withdrawal_id', name=op.f('pk_withdrawals'))
    )
    op.create_index(op.f('ix_withdrawals_worker_id'), 'withdrawals', ['worker_id'], unique=False)
    op.create_table('completion_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('worker_confirmed', sa.Boolean(), nullable=False),
    sa.Column('hiring_party_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_completion_verifications_job_id_jobs')),
    sa.PrimaryKeyConstraint('verification_id', name=op.f('pk_completion_verifications')),
    sa.UniqueConstraint('job_id', name=op.f('uq_completion_verifications_job_id'))
    )
    op.create_table('disputes',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_disputes_job_id_jobs')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.user_id'], name=op.f('fk_disputes_raised_by_users')),
    sa.PrimaryKeyConstraint('dispute_id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_job_id'), 'disputes', ['job_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_job_matches_job_id_jobs')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.user_id'], name=op.f('fk_job_matches_worker_id_workers')),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_job_matches'))
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_worker_id'), 'job_matches', ['worker_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_messages_job_id_jobs')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_job_id'), 'messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('escrow_status', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.CheckConstraint('platform_fee >= 0', name=op.f('ck_payments_platform_fee_non_negative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_payments_job_id_jobs')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments')),
    sa.UniqueConstraint('job_id', name=op.f('uq_payments_job_id'))
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], name=op.f('fk_ratings_from_user_id_users')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name=op.f('fk_ratings_job_id_jobs')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], name=op.f('fk_ratings_to_user_id_users')),
    sa.PrimaryKeyConstraint('rating_id', name=op.f('pk_ratings'))
    )
    op.create_index(op.f('ix_ratings_job_id'), 'ratings', ['job_id'], unique=False)
    op.create_index(op.f('ix_ratings_to_user_id'), 'ratings', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_to_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_job_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_job_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_job_matches_worker_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_disputes_job_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_table('completion_verifications')
    op.drop_index(op.f('ix_withdrawals_worker_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_hiring_party_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_category_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_connections_worker_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_hiring_party_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('workers')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_kyc_user_id'), table_name='kyc')
    op.drop_table('kyc')
    op.drop_table('hiring_parties')
    op.drop_table('users')
    op.drop_table('job_categories')
    # ### end Alembic commands ###
