"""make messages job_id nullable

Revision ID: f42070bde395
Revises: 64f9b9b0c0cf
Create Date: 2026-08-16 03:01:31.820711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42070bde395'
down_revision: Union[str, None] = '64f9b9b0c0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
